import "./globals.css";
import MenuBtnMouse from "../Components/mudarBtmMouse/MenuBtnM";
import Header from "@/Components/Header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <MenuBtnMouse>
          <Header />
          {children}
        </MenuBtnMouse>
      </body>
    </html>
  );
}
