import "./globals.css";
import MenuBtnMouse from "../Components/mudarBtmMouse/MenuBtnM";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuBtnMouse>
          {children}
        </MenuBtnMouse>
      </body>
    </html>
  );
}
